services:
  app:
    image: ghcr.io/imonlytryingtohelp/deletedpostsbot:dev
    container_name: mch-deletedposts
    restart: unless-stopped
    volumes:
      - ./docker-config:/app/config
    environment:
      DPB_REDDIT_CLIENT_ID: "${DPB_REDDIT_CLIENT_ID}"
      DPB_REDDIT_CLIENT_SECRET: "${DPB_REDDIT_CLIENT_SECRET}"
      DPB_REDDIT_USER_AGENT: "${DPB_REDDIT_USER_AGENT}"
      DPB_REDDIT_USERNAME: "${DPB_REDDIT_USERNAME}"
      DPB_REDDIT_PASSWORD: "${DPB_REDDIT_PASSWORD}"
      DPB_REDDIT_SUB_NAME: "${DPB_REDDIT_SUB_NAME}"
      DPB_REDDIT_MAX_DAYS: "${DPB_REDDIT_MAX_DAYS}"            # strings are converted to ints when the
      DPB_REDDIT_MAX_POSTS: "${DPB_REDDIT_MAX_POSTS}"          # corresponding config value is an int
      DPB_REDDIT_SLEEP_MINUTES: "${DPB_REDDIT_SLEEP_MINUTES}"
      DPB_REDDIT_BAN_WIKI_PAGE: "${DPB_REDDIT_BAN_WIKI_PAGE}"
